default:
  image: harbor.shopeemobile.com/undefined/deploy-nodejs:v16

pages:
  stage: deploy
  script:
    - yarn --ignore-engines
    - yarn site
    - mv _site public
  artifacts:
    paths:
      - public
  only:
    - master
