(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["components/popconfirm/demo"],{

/***/ "./node_modules/bisheng/tmp/components-popconfirm-demo.index.js":
/*!**********************************************************************!*\
  !*** ./node_modules/bisheng/tmp/components-popconfirm-demo.index.js ***!
  \**********************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

eval("module.exports = {\n    'async': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/popconfirm/demo/async.md */ \"/Users/lay.zhang/Desktop/shopee/infra-design/node_modules/bisheng/lib/loaders/source-loader!/Users/lay.zhang/Desktop/shopee/infra-design/components/popconfirm/demo/async.md\"),\n    'basic': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/popconfirm/demo/basic.md */ \"/Users/lay.zhang/Desktop/shopee/infra-design/node_modules/bisheng/lib/loaders/source-loader!/Users/lay.zhang/Desktop/shopee/infra-design/components/popconfirm/demo/basic.md\"),\n    'dynamic-trigger': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/popconfirm/demo/dynamic-trigger.md */ \"/Users/lay.zhang/Desktop/shopee/infra-design/node_modules/bisheng/lib/loaders/source-loader!/Users/lay.zhang/Desktop/shopee/infra-design/components/popconfirm/demo/dynamic-trigger.md\"),\n    'icon': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/popconfirm/demo/icon.md */ \"/Users/lay.zhang/Desktop/shopee/infra-design/node_modules/bisheng/lib/loaders/source-loader!/Users/lay.zhang/Desktop/shopee/infra-design/components/popconfirm/demo/icon.md\"),\n    'locale': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/popconfirm/demo/locale.md */ \"/Users/lay.zhang/Desktop/shopee/infra-design/node_modules/bisheng/lib/loaders/source-loader!/Users/lay.zhang/Desktop/shopee/infra-design/components/popconfirm/demo/locale.md\"),\n    'placement': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/popconfirm/demo/placement.md */ \"/Users/lay.zhang/Desktop/shopee/infra-design/node_modules/bisheng/lib/loaders/source-loader!/Users/lay.zhang/Desktop/shopee/infra-design/components/popconfirm/demo/placement.md\"),\n    'promise': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/popconfirm/demo/promise.md */ \"/Users/lay.zhang/Desktop/shopee/infra-design/node_modules/bisheng/lib/loaders/source-loader!/Users/lay.zhang/Desktop/shopee/infra-design/components/popconfirm/demo/promise.md\"),\n}\n\n//# sourceURL=webpack:///./node_modules/bisheng/tmp/components-popconfirm-demo.index.js?");

/***/ })

}]);